fragment PageParts on Page {
  __typename
  type
  title
  slug
  seo {
    __typename
    metaTitle
    metaDescription
    addTitleSuffix
  }
  isDraft
}

fragment PostParts on Post {
  __typename
  title
  slug
  date
  author
  excerpt
  image
  body
}

fragment BlogParts on Blog {
  __typename
  title
  slug
  date
  author
  excerpt
  image
  body
}
