fragment PageParts on Page {
  __typename
  title
  slug
  type
  heroSection {
    __typename
    title
    subtitle
    text
    imageUrl
    imageAlt
    badgeLabel
    button1Label
    button1Url
    button2Label
    button2Url
    button3Label
    button3Url
  }
  introSection {
    __typename
    title
    subtitle
    text
    imageUrl
    imageAlt
  }
  featuredSection {
    __typename
    title
    subtitle
    variant
    colors
  }
  featuredItem1 {
    __typename
    title
    subtitle
    text
    imageUrl
    imageAlt
  }
  featuredItem2 {
    __typename
    title
    subtitle
    text
    imageUrl
    imageAlt
  }
  featuredItem3 {
    __typename
    title
    subtitle
    text
    imageUrl
    imageAlt
  }
  ctaSection {
    __typename
    title
    subtitle
    text
    buttonLabel
    buttonUrl
    colors
  }
  contactSection {
    __typename
    title
    subtitle
    text
    buttonLabel
    buttonUrl
  }
  seo {
    __typename
    metaTitle
    metaDescription
    addTitleSuffix
    socialImage
  }
  isDraft
}

fragment PostParts on Post {
  __typename
  title
  slug
  date
  author
  excerpt
  image
  body
}

fragment DataParts on Data {
  __typename
  type
  title
}
